package claudecompat

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ujzk/tele-agent/internal/testutil/claudetest"
)

// logArgv is a shell script body that appends its argv to log, as
// NUL-separated arguments ending in a NUL and a newline, then runs prog
// with the same arguments.
func logArgv(log, prog string) string {
	return `for a in "$0" "$@"; do printf '%s\0' "$a"; done >> '` + log + `'
printf '\n' >> '` + log + `'
exec ` + prog + ` "$@"
`
}

// invocations reads the argv lists logged by logArgv.
func invocations(t *testing.T, log string) [][]string {
	t.Helper()
	b, err := os.ReadFile(log)
	if err != nil {
		t.Fatalf("no invocation logged: %v", err)
	}
	var out [][]string
	for _, rec := range strings.Split(string(b), "\x00\n") {
		if rec == "" {
			continue
		}
		out = append(out, strings.Split(rec, "\x00"))
	}
	return out
}

func TestSmoke(t *testing.T) {
	claude := claudetest.Require(t)
	api := claudetest.NewAPI(t, claudetest.Say("hello from the script"))
	r := claudetest.Run(t, claude, api, claudetest.Options{Prompt: "hi"})
	if r.Err != nil || r.Output.Result != "hello from the script" {
		t.Fatalf("claude: %v, result %q\nstdout: %s\nstderr: %s", r.Err, r.Output.Result, r.Stdout, r.Stderr)
	}
}

// bashTool runs the Bash tool once with a logging CLAUDE_CODE_SHELL (and
// the extra environment) and returns the shell's invocations and the
// temporary directory given as CLAUDE_CODE_TMPDIR.
func bashTool(t *testing.T, command string, env ...string) (shell, tmpdir string, argvs [][]string) {
	t.Helper()
	claude := claudetest.Require(t)
	bin := filepath.Join(t.TempDir(), "bin")
	if err := os.Mkdir(bin, 0o755); err != nil {
		t.Fatal(err)
	}
	tmpdir = t.TempDir()
	log := filepath.Join(t.TempDir(), "argv")
	shell = claudetest.WriteScript(t, bin, "bash", logArgv(log, "/bin/bash"))
	api := claudetest.NewAPI(t,
		claudetest.Use("Bash", map[string]any{"command": command, "description": "Run a test command"}),
		claudetest.Say("done"),
	)
	r := claudetest.Run(t, claude, api, claudetest.Options{
		Prompt: "run it",
		Args:   []string{"--allowedTools", "Bash"},
		Env:    append([]string{"CLAUDE_CODE_SHELL=" + shell, "CLAUDE_CODE_TMPDIR=" + tmpdir}, env...),
	})
	if r.Err != nil {
		t.Fatalf("claude: %v\nstderr: %s", r.Err, r.Stderr)
	}
	res, ok := api.ToolResult(0)
	if !ok || res.IsError {
		t.Fatalf("Bash tool result %+v (%q)", res, res.ResultText())
	}
	return shell, tmpdir, invocations(t, log)
}

// commandInvocation returns the invocation whose last argument contains
// marker.
func commandInvocation(t *testing.T, argvs [][]string, marker string) []string {
	t.Helper()
	for _, argv := range argvs {
		if strings.Contains(argv[len(argv)-1], marker) {
			return argv
		}
	}
	t.Fatalf("no invocation ran %q; logged %q", marker, argvs)
	return nil
}

// TestClaudeCodeShell pins docs/claude-code.md "CLAUDE_CODE_SHELL".
func TestClaudeCodeShell(t *testing.T) {
	shell, tmpdir, argvs := bashTool(t, "echo tele-marker")
	cmd := commandInvocation(t, argvs, "echo tele-marker")
	t.Logf("command invocation: %q", cmd)
	if len(cmd) != 3 || cmd[0] != shell || cmd[1] != "-c" {
		t.Errorf("argv %q, want [%s -c <command string>]", cmd, shell)
	}
	s := cmd[len(cmd)-1]
	for _, want := range []string{"source ", "eval 'echo tele-marker'", "pwd -P >| " + tmpdir + "/"} {
		if !strings.Contains(s, want) {
			t.Errorf("command string %q lacks %q", s, want)
		}
	}
	// The snapshot is generated by the same shell, as a login shell.
	snap := commandInvocation(t, argvs, "SNAPSHOT_FILE=")
	if len(snap) != 4 || snap[1] != "-c" || snap[2] != "-l" {
		t.Errorf("snapshot invocation %q, want [shell -c -l <script>]", snap[:min(len(snap), 3)])
	}
}

// TestClaudeCodeShellName pins docs/claude-code.md "CLAUDE_CODE_SHELL": a
// shell whose path contains neither bash nor zsh is ignored, which is why
// the shim is named bash.
func TestClaudeCodeShellName(t *testing.T) {
	claude := claudetest.Require(t)
	log := filepath.Join(t.TempDir(), "argv")
	shell := claudetest.WriteScript(t, t.TempDir(), "tele-shell", logArgv(log, "/bin/bash"))
	api := claudetest.NewAPI(t,
		claudetest.Use("Bash", map[string]any{"command": "echo tele-marker", "description": "Print a marker"}),
		claudetest.Say("done"),
	)
	r := claudetest.Run(t, claude, api, claudetest.Options{
		Prompt: "run it",
		Args:   []string{"--allowedTools", "Bash"},
		Env:    []string{"CLAUDE_CODE_SHELL=" + shell},
	})
	if r.Err != nil {
		t.Fatalf("claude: %v\nstderr: %s", r.Err, r.Stderr)
	}
	if res, ok := api.ToolResult(0); !ok || !strings.Contains(res.ResultText(), "tele-marker") {
		t.Fatalf("Bash tool result %+v (%q), want the marker", res, res.ResultText())
	}
	if _, err := os.Stat(log); err == nil {
		t.Fatalf("Claude used %s although its name contains neither bash nor zsh: %q", shell, invocations(t, log))
	}
}

// TestClaudeCodeShellPrefix pins docs/claude-code.md
// "CLAUDE_CODE_SHELL_PREFIX" for the Bash tool: the command string is
// wrapped as '<PREFIX>' '<command string>' and handed to the shell.
func TestClaudeCodeShellPrefix(t *testing.T) {
	dir := t.TempDir()
	prefix := claudetest.WriteScript(t, dir, "tele-exec", `exec /bin/bash -c "$1"`+"\n")
	_, _, argvs := bashTool(t, "echo tele-marker", "CLAUDE_CODE_SHELL_PREFIX="+prefix)
	cmd := commandInvocation(t, argvs, "echo tele-marker")
	t.Logf("command invocation: %q", cmd)
	s := cmd[len(cmd)-1]
	// Two shell words: the prefix and the quoted command string.
	words := shellWords(t, s)
	if len(words) != 2 || words[0] != prefix || !strings.Contains(words[1], "eval 'echo tele-marker'") {
		t.Errorf("command string %q splits into %q, want [%s <command string>]", s, words, prefix)
	}
}

// runSh runs script with sh -c and args, returning its stdout.
func runSh(ctx context.Context, script string, args ...string) (string, error) {
	out, err := exec.CommandContext(ctx, "/bin/sh", append([]string{"-c", script, "sh"}, args...)...).Output()
	return string(out), err
}
